# This formula is regenerated by the tael CLI release workflow from
# packaging/homebrew/tael.rb.tmpl in taelio/cli. Manual edits here will be
# overwritten on the next release; change the template instead.
class Tael < Formula
  desc "Command-line interface for the Tael AI DevOps platform"
  homepage "https://tael.io"
  version "0.1.0"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/taelio/cli/releases/download/v#{version}/tael-darwin-arm64"
      sha256 "5367bab15712c434af379ef02aef982e52ac2fd061aca9eaaecaa5cba1735ef7"
    end
    on_intel do
      url "https://github.com/taelio/cli/releases/download/v#{version}/tael-darwin-amd64"
      sha256 "3092619fa60eb7d3fa0f6102fcb255a3ae309c6579d4dd5a4f6c5744ef5c211c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/taelio/cli/releases/download/v#{version}/tael-linux-arm64"
      sha256 "a68105f16a05e019b753b0cee5ef21a6c37de197140842580765648c643482c9"
    end
    on_intel do
      url "https://github.com/taelio/cli/releases/download/v#{version}/tael-linux-amd64"
      sha256 "66419e12d520faf8440b79c3000fdcd6923a122fd8d87d507cfa5d9fd99c6967"
    end
  end

  def install
    # Release assets are bare binaries rather than archives, so the download
    # carries no execute bit; set it before anything runs the binary.
    bin.install Dir["tael-*"].first => "tael"
    chmod 0755, bin/"tael"
    generate_completions_from_executable(bin/"tael", "completion")
  end

  test do
    assert_match "tael v#{version}", shell_output("#{bin}/tael version")
  end
end
