# This formula is regenerated by the tael CLI release workflow from
# packaging/homebrew/tael.rb.tmpl in taelio/cli. Manual edits here will be
# overwritten on the next release; change the template instead.
class Tael < Formula
  desc "Command-line interface for the Tael AI DevOps platform"
  homepage "https://tael.io"
  version "0.5.0"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/taelio/cli/releases/download/v#{version}/tael-darwin-arm64"
      sha256 "31e886dc63d5bb97f8fc25f481249bb4023a686a405d9ea0d8b16925e19baaa9"
    end
    on_intel do
      url "https://github.com/taelio/cli/releases/download/v#{version}/tael-darwin-amd64"
      sha256 "92e887fa4269bf60437022bc7f379e01d3df49bb9706768b581d039678e1155a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/taelio/cli/releases/download/v#{version}/tael-linux-arm64"
      sha256 "74e3df40d41efc84b2f8d54787707c2cae94d843c6ceed9914d41a0b5db7cbbd"
    end
    on_intel do
      url "https://github.com/taelio/cli/releases/download/v#{version}/tael-linux-amd64"
      sha256 "ca5b37077fbd2b7faf4c600656f3e2629e6a1636c427b063c6bdb39ed0479cf2"
    end
  end

  def install
    # Release assets are bare binaries rather than archives, so the download
    # carries no execute bit; set it before anything runs the binary.
    bin.install Dir["tael-*"].first => "tael"
    chmod 0755, bin/"tael"
    generate_completions_from_executable(bin/"tael", "completion")
  end

  test do
    assert_match "tael v#{version}", shell_output("#{bin}/tael version")
  end
end
